title: maxvoltar.photo
email: tim@maxvoltar.be
author:
  name: Tim Van Damme
  email: tim@maxvoltar.be #optional
  website: https://maxvoltar.com
description: >- # this means to ignore newlines until "baseurl:"
  @maxvoltar's minimalistic, self-hosted photo stream.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maxvoltar.photo" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maxvoltar
github_username: maxvoltar
instagram_username: maxvoltar

# Build settings
plugins:
  - jekyll-exif-data

image_processing:
  large:
    source: photos/original
    destination: photos/large
    resize_to_limit: [2048, 2048]
    saver:
      strip: true
  thumbnail:
    source: photos/original
    destination: photos/thumbnail
    resize_to_limit: [640, 640]
    saver:
      strip: true
  tint:
    source: photos/original
    destination: photos/tint
    resize_to_fill: [1,1]
    saver:
      strip: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
